### ISSUE TITLE
Missing data functions not working

### ISSUE THREAD

**Issue by mikaelr88** [bkeller2/mlmpower#3]
`mechanism = MAR(0.25)` or `mechanism = MCAR(0.25)` do not work when I try to replicate the CRAN .pdf I receive the error:
`Error in MCAR(0.25) : could not find function "MCAR"` or `Error in MAR(0.25) : could not find function "MAR"`

**Comment by bkeller2** [comment]
@mikaelr88

Are you sure you are on the latest version (1.0.4)? These functions were added in the most recent update.

Can you please copy and paste the output from `sessionInfo()` to verify?

**Comment by mikaelr88** [comment]
Apologies, I saw that I was using 1.03, once I updated to 1.04 the issue was fixed.

**Comment by bkeller2** [comment]
Not a problem glad it's working!
