### ISSUE TITLE
Feature request: centered simulated data

### ISSUE THREAD

**Issue by mkshaw** [bkeller2/mlmpower#5]
Hi Brian,

Thanks so much for your work on this package! I'm using it for a simulation study, and am wondering if you would consider implementing an option to generate different levels of centering for level-1 predictors in the `generate` function. For example, I'm looking to simulate data with level-1 variables centered-within-cluster. I can do it manually after data generation, it would just be convenient to have it done at source. 

Thanks again for the package!

**Comment by bkeller2** [comment]
Hello!

I will need more context about how you would like to use it so I can incorporate the suggestion.

Currently, the centering is handled automatically with the `analyze()` function for someone. The centering strategy chosen is directly related to the variable specification. For example, when analyzed, a level-1 variable with icc = 0 will be CWC'ed. To obtain a level-1 variable decomposed into its level-1 and level-2 effect, a level-1 variable with icc = 0 and a level-2 variable are required to represent the cluster mean. All of this relates to the analytically solved parameters, so any other centering strategy would not give the appropriate estimates.

I could add a `center()` function if you want to use it purely for data generation. The question, then, is how it would be best implemented. For example, by default, it could provide the same centering produced by `analyze()` function in `mlmpower`, and if you wanted to override a specific variable, it could be something like `mydata |> center(x2 = cwc) -> mydata_c`.

Is something like that what you are thinking of?

**Comment by mkshaw** [comment]
Yes, that's exactly what I'm thinking of!

**Comment by bkeller2** [comment]
I've added this functionality with ac8c755a23792d1885586c516b1821cda8eee6ee.

I've submitted a new version to CRAN, so it will take a while to update it.

You can always use the dev build with:

```r
remotes::install_github('bkeller2/mlmpower', build_vignettes = TRUE)
```

**Comment by mkshaw** [comment]
Thank you for implementing that so quickly!
